#!/bin/bash

clear && cd "$(dirname "$(realpath "$0")")" || echo

if [ ! -d "$HOME/kodo" ]; then
    mkdir "$HOME/kodo"
fi
if [ ! -f "$HOME/kodo/kodo.txt" ]; then
    touch "$HOME/kodo/.kodo.txt"
fi

__OS_NOTICE__=0
export __OS_NOTICE__

#  "nul"     
#  "linux"   
#  "windows" 
__OS__="nul"
export __OS__

# Server
SERVERS_NEXT=0
export SERVERS_NEXT

# Compat
__PAWNCC_NAME__="nul"
export __PAWNCC_NAME__
__SAMP_SERVER=""
export __SAMP_SERVER

# Zapman
ZAPMAN_ainstall_Encrypt=""
export ZAPMAN_ainstall_Encrypt
zapman_ainstall_SIZEOF=0
export zapman_ainstall_SIZEOF
ZAPMAN_ainstall_Decrypt=""
export ZAPMAN_ainstall_Decrypt

# Vireon A.I
VIREON_token_Encrypt=""
export VIREON_token_Encrypt
VIREON_token_Decrypt=""
export VIREON_token_Decrypt

# Notice Var
kodo_t_save_messages=0
export kodo_t_save_messages
kodo_t_save_notice=0
export kodo_t_save_notice
kodo_t_module_loaded=0
export kodo_t_module_loaded

# General
shell_TITLE=""
export shell_TITLE
shell_DIR="$(dirname "$(realpath "$0")")"
export shell_DIR
shell_NAME="$(basename "$0")"
export shell_NAME

# Licenses
LICENSES="MIT Licenses."
export LICENSES

# Compiler
__cache_save_compile=".cache/compiler.log"
export __cache_save_compile

compiler_MODE="nul"
export compiler_MODE
COMPILER_PAWNCC=""
export COMPILER_PAWNCC
COMPILER_NEXT=0
export COMPILER_NEXT

commands_OPAMX=()
export commands_OPAMX

# Struct of kodo.toml
toml_INCLUDE="nul"
export toml_INCLUDE
toml_EXCLUDE="nul"
export toml_EXCLUDE
toml_ZAPMAN_INCLUDE="nul"
export toml_ZAPMAN_INCLUDE
toml_ZAPMAN_PLUGINS="nul"
export toml_ZAPMAN_PLUGINS
toml_LOG_SERV="nul"
export toml_LOG_SERV
toml_SERVER_CONFIG="nul"
export toml_SERVER_CONFIG
toml_FILE_SERV="nul"
export toml_FILE_SERV
toml_EXE_SERV="nul"
export toml_EXE_SERV
toml_RM_CACHE="nul"
export toml_RM_CACHE
toml_VIREON_MODEL="nul"
export toml_VIREON_MODEL
toml_VIREON_BIODATA="nul"
export toml_VIREON_BIODATA
toml_VIREON_TOKEN="nul"
export toml_VIREON_TOKEN
toml_AMX_OPT_F="nul"
export toml_AMX_OPT_F

function collor_yellow() {
# Color Text {Yellow}
# ' echo "$(collor_yellow "label")" content '
COLOR_Y="\e[33m"
    local color="$COLOR_Y"
    local label="$1"
    echo -e "${color}${label}\e[0m"
}
export collor_yellow

function print_yellow() {
    if [ -n "$2" ]; then
        echo -e "$(collor_yellow "$1") $2"
    elif [ -z "$2" ]; then
        echo -e "$(collor_yellow "$1")"
    fi
}

function collor_green() {
# Color Text {Green}
# ' echo "$(collor_green "label")" content '
COLOR_G="\e[32m"
    local color="$COLOR_G"
    local label="$1"
    echo -e "${color}${label}\e[0m"
}
export collor_green

function print_green() {
    if [ -n "$2" ]; then
        echo -e "$(collor_green "$1") $2"
    elif [ -z "$2" ]; then
        echo -e "$(collor_green "$1")"
    fi
}

function collor_red() {
# Color Text {Red}
# ' echo "$(collor_red "label")" content '
COLOR_R="\e[91m"
    local color="$COLOR_R"
    local label="$1"
    echo -e "${color}${label}\e[0m" 
}
export collor_red

function print_red() {
    if [ -n "$2" ]; then
        echo -e "$(collor_red "$1") $2"
    elif [ -z "$2" ]; then
        echo -e "$(collor_red "$1")"
    fi
}

function collor_gray() {
# Color Text {Gray} 
# ' echo "$(collor_gray "label")" content '
COLOR_A="\e[97m"
    local color="$COLOR_A"
    local label="$1"
    echo -e "${color}${label}\e[0m"
}
export collor_gray

function print_gray() {
    if [ -n "$2" ]; then
        echo -e "$(collor_gray "$1") $2"
    elif [ -z "$2" ]; then
        echo -e "$(collor_gray "$1")"
    fi
}

function bash_title() {
    echo -ne "\033]0;$1\007"
}

function kodo_t_TITLE()
{
# Tile Functions
# ' kodo_t_TITLE "title" '
    local title=$1
    shell_TITLE="$title"
    bash_title "$shell_TITLE"
}
export kodo_t_TITLE

if [ ! -d ".cache" ]; then
    mkdir ".cache" && chmod +x ".cache"
fi

function SIGNAL_KILL()
{
    kd_table="kill"
    mode_KODO "$kd_table"
}

function ignore_this() {
    # ignore succes/error/warning to null
    "$@" > /dev/null 2>&1
}
export ignore_this

function rest_var() {
    # Reset Variables #

    : ' Checking before unset '
    [ -n "${compiler_MODE+x}" ] && unset compiler_MODE
    [ -n "${COMPILER_PAWNCC+x}" ] && unset COMPILER_PAWNCC
    [ -n "${COMPILER_NEXT+x}" ] && unset COMPILER_NEXT
    [ -n "${SERVERS_NEXT+x}" ] && unset SERVERS_NEXT

    compiler_MODE="nul"
    COMPILER_PAWNCC=""
    COMPILER_NEXT=0
    SERVERS_NEXT=0
    zapman_ainstall_SIZEOF=0
}

function @KODO_TOML_CREATE() {
    cd "$shell_DIR" >/dev/null 2>&1 || echo ""

    u_openmp=$(find . -maxdepth 1 -type f \( -name "omp-server" -o -name "omp-server.exe" \) | head -n 1)
    u_samp=$(find . -maxdepth 1 -type f \( -name "samp03svr" -o -name "samp-server.exe" \) | head -n 1)

    if [[ -n "$u_samp" ]] && [[ -n "$u_openmp" ]]; then
        __SAMP_SERVER="samp"
    elif [[ -n "$u_samp" ]]; then
        __SAMP_SERVER="samp"
    elif [[ -n "$u_openmp" ]]; then
        __SAMP_SERVER="omp"
    else
        __SAMP_SERVER="samp"
    fi

    if [ ! -f "kodo.toml" ]; then
    local executable=""
    local log=""
    local config=""
    local include=""

    if [[ "$__SAMP_SERVER" == "samp" ]]; then
        log="server_log.txt"
        config="server.cfg"
        include="pawno/include"
        executable="samp-server.exe"
        [[ "$__OS__" == "linux" ]] && executable="samp03svr"
    elif [[ "$__SAMP_SERVER" == "omp" ]]; then
        log="log.txt"
        config="config.json"
        include="qawno/include"
        executable="omp-server.exe"
        [[ "$__OS__" == "linux" ]] && executable="omp-server"
    fi

    cat > kodo.toml <<EOF
[paths]
include_paths = "$include"
include_dir = "zapman/include"
plugins_dir = "zapman/plugins"

[server]
log = "$log"
config = "$config"
init = "main.pwn"
executable = "$executable"
remcache_auto = false

[vireon]
model = "qwen-2.5-32b"
profile = "hello vireom, your name is john"
token = "gsk_abcd"

[compiler]
exclude_paths = ["includes1/", "includes2/", "includes3/"]
amx_flags = ['-d2', '-;+', '-(+', '-Z+']
EOF
fi
}

function @LOAD_KODO_TOML()
{
    local toml_data
    toml_data=$(tomlq -c '.' kodo.toml)

    # paths
    toml_INCLUDE=$(echo "$toml_data" | jq -r '.paths.include_paths')
    [[ "$toml_INCLUDE" == "nul" ]] && print_red "error:" "failed to load \"include_paths\""

    toml_ZAPMAN_INCLUDE=$(echo "$toml_data" | jq -r '.paths.include_dir')
    [[ "$toml_ZAPMAN_INCLUDE" == "nul" ]] && print_red "error:" "failed to load \"include_dir\""

    toml_ZAPMAN_PLUGINS=$(echo "$toml_data" | jq -r '.paths.plugins_dir')
    [[ "$toml_ZAPMAN_PLUGINS" == "nul" ]] && print_red "error:" "failed to load \"plugins_dir\""

    # server
    toml_LOG_SERV=$(echo "$toml_data" | jq -r '.server.log')
    [[ "$toml_LOG_SERV" == "nul" ]] && print_red "error:" "failed to load \"log\""

    toml_SERVER_CONFIG=$(echo "$toml_data" | jq -r '.server.config')
    [[ "$toml_SERVER_CONFIG" == "nul" ]] && print_red "error:" "failed to load \"config\""

    toml_FILE_SERV=$(echo "$toml_data" | jq -r '.server.init')
    [[ "$toml_FILE_SERV" == "nul" ]] && print_red "error:" "failed to load \"init\""

    toml_EXE_SERV=$(echo "$toml_data" | jq -r '.server.executable')
    [[ "$toml_EXE_SERV" == "nul" ]] && print_red "error:" "failed to load \"executable\""

    toml_RM_CACHE=$(echo "$toml_data" | jq -r '.server.remcache_auto')
    [[ "$toml_RM_CACHE" == "nul" ]] && print_red "error:" "failed to load \"remcache_auto\""

    # vireon
    toml_VIREON_MODEL=$(echo "$toml_data" | jq -r '.vireon.model')
    [[ "$toml_VIREON_MODEL" == "nul" ]] && print_red "error:" "failed to load \"model\""

    toml_VIREON_BIODATA=$(echo "$toml_data" | jq -r '.vireon.profile')
    [[ "$toml_VIREON_BIODATA" == "nul" ]] && print_red "error:" "failed to load \"profile\""

    toml_VIREON_TOKEN=$(echo "$toml_data" | jq -r '.vireon.token')
    [[ "$toml_VIREON_TOKEN" == "nul" ]] && print_red "error:" "failed to load \"token\""

    # compiler
    toml_EXCLUDE=$(echo "$toml_data" | jq -r '.compiler.exclude_paths[]?' | xargs -I {} echo -n "-i\"{}\" " )
    [[ -z "$toml_EXCLUDE" ]] && print_red "error:" "failed to load \"exclude_paths\""

    toml_AMX_OPT_F=$(echo "$toml_data" | jq -r '.compiler.amx_flags[]?' | xargs)
    [[ -z "$toml_AMX_OPT_F" ]] && print_red "error:" "failed to load \"amx_flags\""
}

function struct_kodo_t_main() {
    local kodo_t_missing_cmds=()
    local kodo_t_missing_save_cmds

    for kodo_t_missing_save_cmds in python3 wget curl grep awk sed tr jq tomlq aria2c openssl; do
        # python3 wget curl grep awk sed tr jq ariac2 openssl #
        if ! command -v "$kodo_t_missing_save_cmds" &>/dev/null; then
            if [ "$kodo_t_missing_save_cmds" = "aria2c" ]; then
                kodo_t_missing_cmds+=("aria2")
            else
                kodo_t_missing_cmds+=("$kodo_t_missing_save_cmds")
            fi
        fi
    done

    if ((${#kodo_t_missing_cmds[@]} > 0)); then
        if [ "$kodo_t_save_notice" -ne 1 ]; then
            print_red " Missing packages:" "${kodo_t_missing_cmds[*]}"
            printf "\e]8;;https://github.com/vilksons/kodo/wiki/Required-Packages\e\\ Please see here for more.\e]8;;\e\\"
            echo
            ignore_this sleep 1.0
        fi
    else
        if [ "$kodo_t_save_notice" -ne 1 ]; then
            # Recheck Sync
            if [ -f ".sync" ]; then
                shred -u .sync
                if [ -d "$shell_DIR/.kodo" ]; then
                    rm -rf ".kodo"
                fi
                ignore_this sleep 0.10
            fi

            if [ ! -d ".kodo" ]; then
                mkdir -p ".kodo/python" && chmod +x ".kodo"
            fi

            function kodo_t_pack() {
                : ' Install or Load modules '
                if [ -f "$shell_DIR/$1" ] && [ "$kodo_t_module_loaded" -ne 1 ]; then
                    chmod +x "$shell_DIR/$1"
                    if [[ "$1" == ".kodo/python/wpython" ]]; then
                        source <(python3 .kodo/python/wpython) || sleep 1.0
                    else
                        if [[ "$1" == ".kodo/compat.kd" ]]; then
                            source "$shell_DIR/$1" || sleep 1.0
                            compat_now ""
                        else
                            source "$shell_DIR/$1" || sleep 1.0
                        fi
                    fi

                    if [ "$kodo_t_module_loaded" -eq 1 ]; then
                        print_green "warn:" "err.. need to kill after installing \"succes\".."
                        print_green " killing.."
                        sleep 0.999 && SIGNAL_KILL "" && typeof ""
                    fi
                else
                    bash_title "Waiting resources.."

                    if [ "$3" != "silent" ]; then
                        wget -q -O "$shell_DIR/$1" "$2" &>/dev/null
                    else
                        wget -q -O "$shell_DIR/$1" "$2" &>/dev/null &
                    fi

                    if [ "$3" = "end" ]; then
                        kodo_t_module_loaded=1
                        wget -q -O "$shell_DIR/$1" "$2" &>/dev/null &
                        clear && cd "$(dirname "$(realpath "$0")")" || echo
                        print_yellow "install succes!"
                        print_green " killing.."
                        sleep 0.999 && SIGNAL_KILL "" && typeof ""
                    fi
                fi
            }

            kodo_t_pack ".kodo/python/wpython" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Scripts/wpython" ""

            cd "$shell_DIR/.kodo" >/dev/null 2>&1 || echo ""
            
            kodo_t_pack ".kodo/security.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Security/security.kd" "silent" 

            kodo_t_pack ".kodo/compat.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Compat/compat.kd" "compat" 

            kodo_t_pack ".kodo/compiler.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Compiler/compiler.kd" "silent" 

            kodo_t_pack ".kodo/zapman.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Zapman/zapman.kd" "silent" 

            kodo_t_pack ".kodo/samp.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Package/samp.kd" "silent" 

            kodo_t_pack ".kodo/pawncc.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Package/pawncc.kd" "silent" 

            kodo_t_pack ".kodo/misc.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Misc/misc.kd" "silent"

            kodo_t_pack ".kodo/vireon.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Vireon/vireon.kd" "silent" 

            kodo_t_pack ".kodo/server.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Server/server.kd" "end"
            
            kodo_t_save_notice=1

            cd "$shell_DIR" >/dev/null 2>&1 || echo ""
            ignore_this @KODO_TOML_CREATE "" &&
            ignore_this @LOAD_KODO_TOML ""
        fi
    fi

    if [ "$kodo_t_save_notice" -eq 1 ]; then
        @ENCRYPTION_CREATE ""
        @ENCRYPTION_TOKEN ""
    fi
    
    rest_var "" && typeof ""
}
export struct_kodo_t_main

function typeof() {
    if [ "$kodo_t_save_messages" -ne 1 ]; then
        kodo_t_save_messages=1
        printf "Welcome to Kodo!"
        echo
    fi
    
    if [ "$kodo_t_module_loaded" != 1 ]; then
        kodo_t_TITLE "Kodo Mode"
    fi
    
    HISTFILE="$HOME/kodo/.kodo.txt"
    touch "$HISTFILE"

    history -r "$HISTFILE"

    read -e -r -p "kodo:~$ " kd_table
    
    if [ -n "$kd_table" ]; then
        echo "$kd_table" >> "$HISTFILE"
    fi

    mode_KODO "$kd_table"
}
export typeof

function mode_KODO() {
    : ' WARNING '
    #   always remember to end use 'end_kodo_t_main' or 'struct_kodo_t_main' so it doesn't crash or exit Kodo
    
    local trigger_kd="kodo"

    case "$kd_table" in
        "compile"*)
            kodo_t_TITLE "Compiler"

            local commands_ARGS="${kd_table#compile }"
            local commands_INPUT=""

            for arg in $commands_ARGS; do
                if [ -z "$commands_INPUT" ]; then
                    commands_INPUT="$arg"
                else
                    commands_OPAMX+=("$arg")
                fi
            done

            kodo_init_compilers "$commands_INPUT"

            end_kodo_t_main ""
            ;;
        "running"*)
            kodo_t_TITLE "Running"
            
            local commands_ARGS="${kd_table#running }"
            
            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                space_servers ""
            fi

            SERVERS_NEXT=1

            if [[ "$commands_INPUT" == "." ]]; then
                space_servers "" || {
                    if [ "$kodo_t_module_loaded" -eq 1 ]; then
                        print_green "warn:" "err.. need to kill after installing \"succes\".."
                        print_green " killing.."
                        sleep 0.999 && SIGNAL_KILL "" && typeof ""
                    fi
                }
            else
                space_wargs_servers "$commands_INPUT" || {
                    if [ "$kodo_t_module_loaded" -eq 1 ]; then
                        print_green "warn:" "err.. need to kill after installing \"succes\".."
                        print_green " killing.."
                        sleep 0.999 && SIGNAL_KILL "" && typeof ""
                    fi
                }
            fi
            end_kodo_t_main ""
            ;;
        "irunn")
            kodo_t_TITLE "Compile & Running"

            compiler_MODE="false"
            kodo_compilers "" || {
                if [ "$kodo_t_module_loaded" -eq 1 ]; then
                    print_green "warn:" "err.. need to kill after installing \"succes\".."
                    print_green " killing.."
                    sleep 0.999 && SIGNAL_KILL "" && typeof ""
                fi
            }
            ;;
        "debug"*)
            kodo_t_TITLE "Debugging"

            local commands_ARGS="${kd_table#debug }"
            
            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                print_gray ":: Enter GM Name:"
                while true; do
                    read -r -p ">>> " commands_INPUT
                    [[ -n "$commands_INPUT" ]] && break
                done
            fi

            SERVERS_NEXT=2
            
            if [[ "$commands_INPUT" == "." ]]; then
                space_servers "" || {
                    if [ "$kodo_t_module_loaded" -eq 1 ]; then
                        print_green "warn:" "err.. need to kill after installing \"succes\".."
                        print_green " killing.."
                        sleep 0.999 && SIGNAL_KILL "" && typeof ""
                    fi
                }
            else
                space_wargs_servers "$commands_INPUT" || {
                    if [ "$kodo_t_module_loaded" -eq 1 ]; then
                        print_green "warn:" "err.. need to kill after installing \"succes\".."
                        print_green " killing.."
                        sleep 0.999 && SIGNAL_KILL "" && typeof ""
                    fi
                }
            fi
            end_kodo_t_main ""
            ;;
        "stop")
            kodo_t_TITLE "Stop"

            ignore_this pkill -9 -f "$toml_EXE_SERV"

            end_kodo_t_main ""
            ;;
        "restart")
            kodo_t_TITLE "Restart"

            ignore_this pkill -9 -f "$toml_EXE_SERV" && sleep 1
            space_servers ""

            end_kodo_t_main ""
            ;;
        "gamemode")
            kodo_t_TITLE "Downloads | GameMode"

            struct_choice_samp ""

            end_kodo_t_main "" || {
                if [ "$kodo_t_module_loaded" -eq 1 ]; then
                    print_green "warn:" "err.. need to kill after installing \"succes\".."
                    print_green " killing.."
                    sleep 0.999 && SIGNAL_KILL "" && typeof ""
                fi
            }
            ;;
        "pawncc")
            kodo_t_TITLE "Downloads | PawnCC"

            struct_choice_pawncc ""

            end_kodo_t_main "" || {
                if [ "$kodo_t_module_loaded" -eq 1 ]; then
                    print_green "warn:" "err.. need to kill after installing \"succes\".."
                    print_green " killing.."
                    sleep 0.999 && SIGNAL_KILL "" && typeof ""
                fi
            }
            ;;
        "cat"*)
            kodo_t_TITLE "Cat"

            local commands_ARGS="${kd_table#cat }"
            
            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                print_gray ":: Enter File Name:"
                while true; do
                    read -r -p ">>> " commands_INPUT
                    [[ -n "$commands_INPUT" ]] && break
                done
            fi

            cat "$commands_INPUT"
            echo
            end_kodo_t_main ""
            ;;
        "directory"*)
            kodo_t_TITLE "Directory - $shell_DIR"

            local commands_ARGS="${kd_table#directory }"
            
            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                ls -a
                end_kodo_t_main ""
            fi

            ignore_this cd "$commands_INPUT" && ls -a && shell_TITLE="directory - $shell_DIR" && bash_title "$shell_TITLE" || echo
            struct_kodo_t_main ""
            ;;
        "ls")
            ls -a
            struct_kodo_t_main ""
            ;;
        "kill")
            kodo_t_save_notice=0
            kodo_t_save_messages=0
            
            ignore_this clear
            ignore_this sleep 0.10
            cd "$shell_DIR" || echo
            chmod +x "$shell_NAME"
            exec bash ./"$shell_NAME"
            ;;
        "sync"*)
            if [[ "$kd_table" == "sync" ]]; then
                kodo_t_TITLE "Sync"
            fi

            local commands_ARGS="${kd_table#sync }"

            local latest current
            latest=$(curl -s "https://api.github.com/repos/vilksons/kodo/commits/kodo" | grep -o '"sha": "[^"]*' | awk -F': "' '{print $2}')
            current=$(cat "$shell_DIR/.itskodo" 2>/dev/null)

            if [[ "$latest" == "$current" ]]; then
                echo "warning: $shell_NAME is up to date, Nothing to do."
                end_kodo_t_main ""
            else
                print_gray ":: New Commits Found..: Commits (SHA1): "
                echo "$latest"

                read -r -n1 -p ":: Do you want to continue Sync Kodo? [y/n] " PERMISSION_NEED_S
                echo
                [[ -z "$PERMISSION_NEED_S" ]] && PERMISSION_NEED_S="Y"

                case "$PERMISSION_NEED_S" in
                    [Yy])
                        if [[ -d "$shell_DIR/.kodo" ]]; then
                            rm -rf "$shell_DIR/.kodo"
                        fi
                        if [ ! -d ".kodo" ]; then
                            mkdir -p ".kodo/python" && chmod +x ".kodo"
                        fi

                        echo "$latest" > "$shell_DIR/.itskodo"
                    
                    function __modular__()
                    {
                        kodo_t_TITLE "Sync | Upgrade"

                        echo "Upgrading.."
                        
                        local __kodo_modular__=(
                            "Security/security.kd"
                            "Compat/compat.kd"
                            "Zapman/zapman.kd"
                            "Package/samp.kd"
                            "Package/pawncc.kd"
                            "Server/server.kd"
                            "Misc/misc.kd"
                            "Vireon/vireon.kd"
                            "Compiler/compiler.kd"
                        )

                        cd "$shell_DIR/.kodo" >/dev/null 2>&1 || echo ""

                        for __file__ in "${__kodo_modular__[@]}"; do
                            wget -q --show-progress -O "$(basename "$__file__")" \
                                "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/$__file__" \
                                || { touch "$shell_DIR/.sync"; }
                        done

                        cd "$shell_DIR/.kodo/python" >/dev/null 2>&1 || echo ""
                        wget -q --show-progress -O "wpython" \
                            "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Scripts/wpython" &&
                        cd "$shell_DIR" >/dev/null 2>&1 || echo ""
                        wget -q --show-progress -O "workspace" \
                            "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Scripts/workspace"
                    }
                        
                        if  [ "$kd_table" = "sync" ]; then
                            __modular__ ""
                        elif [ "$commands_ARGS" = "update" ]; then
                            kodo_t_TITLE "Sync | Update"

                            echo "Updating.."

                            cd "$shell_DIR" || echo ""
                            wget -q --show-progress -O "workspace" \
                                "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Scripts/workspace"
                        else
                            __modular__ ""
                        fi
                        
                        chmod +x "$shell_DIR/workspace"
                        ignore_this sleep 1
                        bash "$shell_DIR/workspace"
                        ;;
                    *)
                        end_kodo_t_main ""
                        ;;
                esac
            fi
            ;;
        "toml")
            if [ -f "$shell_DIR/kodo.toml" ]; then
                mv kodo.toml kodo.toml.old.txt
            fi

            kodo_t_module_loaded=0
            struct_kodo_t_main ""
            ;;
        "checksums"*)
            kodo_t_TITLE "Checksums"

            local commands_ARGS="${kd_table#checksums }"

            ignore_this cd "$shell_DIR" || echo ""

            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                echo "sha1:" && sha1sum "$shell_NAME" && echo "sha256:" && sha256sum "$shell_NAME" && echo "md5:" && md5sum "$shell_NAME"
                end_kodo_t_main ""
            fi

            for algo in $commands_INPUT; do
                if [[ "$algo" == "sha1" ]]; then
                    echo "sha1:" && sha1sum "$shell_NAME"
                elif [[ "$algo" == "sha256" ]]; then
                    echo "sha256:" && sha256sum "$shell_NAME"
                elif [[ "$algo" == "md5" ]]; then
                    echo "md5:" && md5sum "$shell_NAME"
                else
                    echo "Invalid option: $algo (use sha1, sha256, md5)"
                fi
            done

            end_kodo_t_main ""
            ;;
        "exit"*)
            kodo_t_TITLE "Exit"

            local commands_ARGS="${kd_table#exit }"

            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                ignore_this sleep 0.100 &&
                bash
            fi
            bash
            ;;
        "vireon"*)
            kodo_t_TITLE "Vireon Chat A.I"

            local commands_ARGS="${kd_table#vireon }"

            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                print_gray ":: Enter Question:"
                while true; do
                    read -r -p ">>> " commands_INPUT
                    [[ -n "$commands_INPUT" ]] && break
                done
            fi
            
            kodo_vireon "$commands_INPUT"
            ;;
        "nano"*)
            if ! command -v nano &> /dev/null; then
                print_red "crit:" "nano not found!, install first."
                end_kodo_t_main ""
            fi
            
            kodo_t_TITLE "GNU/Nano"
            
            local commands_ARGS="${kd_table#nano }"

            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                print_gray ":: Enter Names:"
                while true; do
                    read -r -p ">>> " commands_INPUT
                    [[ -n "$commands_INPUT" ]] && break
                done
            fi

            nano "$commands_INPUT"
            end_kodo_t_main ""
            ;;
        "remcac")
            kodo_t_TITLE "Remove Cache"

            if [ "$compiler_MODE" != "nul" ]; then
                print_red "crit:" "can't remove cache!."
                end_kodo_t_main ""
            fi

            if [ ! -f "$shell_DIR/.cache/zapman" ] && [ ! -f "$shell_DIR/.cache/compiler.log" ]; then
                echo "no cache found."
                end_kodo_t_main ""
            fi

            if [ -f "$shell_DIR/.cache/zapman" ]; then
                print_gray ":: Cache Dir: $shell_DIR/.cache/tlizapmangpac"
                read -r -p ":: Do you want to remove ALL files from $shell_DIR/.cache/zapman? [y/n] " PERMISSION_NEED_RC
                echo
                [[ -z "$PERMISSION_NEED_RC" ]] && PERMISSION_NEED_RC="Y"

                while true; do
                    case "$PERMISSION_NEED_RC" in
                        [Yy])
                            cd "$shell_DIR" || echo
                            shred -u ".cache/zapman" && print_yellow " successfully"
                            sleep 1
                            break
                            ;;
                        *)
                            echo "Operation cancelled"
                            break
                            ;;
                    esac
                done
            fi

            if [ -f "$shell_DIR/.cache/compiler.log" ]; then
                print_gray ":: Cache Dir: $shell_DIR/.cache/compiler.log"
                read -r -p ":: Do you want to remove ALL files from $shell_DIR/.cache/compiler.log? [y/n] " PERMISSION_NEED_RC
                echo
                [[ -z "$PERMISSION_NEED_RC" ]] && PERMISSION_NEED_RC="Y"

                while true; do
                    case "$PERMISSION_NEED_RC" in
                        [Yy])
                            cd "$shell_DIR" || echo
                            shred -u ".cache/compiler.log" && print_yellow " successfully"
                            sleep 1
                            end_kodo_t_main ""
                            ;;
                        *)
                            echo "Operation cancelled"
                            end_kodo_t_main ""
                            ;;
                    esac
                done
            else
                end_kodo_t_main ""
            fi
            ;;
        "fetch")
            fetch_now ""
            ;;
        "zapman")
            mode_ZAPMAN "" || {
                if [ "$kodo_t_module_loaded" -eq 1 ]; then
                    print_green "warn:" "err.. need to kill after installing \"succes\".."
                    print_green " killing.."
                    sleep 0.999 && SIGNAL_KILL "" && typeof ""
                fi
            }
            ;;
        "clear" | "c" | "C" | "cc")
            kodo_t_save_messages=0
            clear; echo -ne "\033[3J"
            struct_kodo_t_main ""
            ;;
        "modular"*)
            kodo_t_TITLE "Modular Checking | Debugging"

            function kodo_t_modular_load() {
                : ' Install or Load modules '
                if [ -f "$shell_DIR/$1" ]; then
                    chmod +x "$shell_DIR/$1"

                    echo "[DEBUG]: $1"

                    if [[ "$1" == ".kodo/python/wpython" ]]; then
                        python3 .kodo/python/wpython && print_yellow "Succes"
                    else
                        source "$shell_DIR/$1" && print_yellow "Succes"
                    fi
                fi
            }

            local commands_ARGS="${kd_table#modular }"

            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                commands_INPUT="$commands_ARGS"

                if [ -f "$commands_INPUT" ]; then
                    printf_red "error:" "$commands_INPUT not found!."
                    struct_kodo_t_main ""
                fi

                kodo_t_modular_load "$commands_INPUT" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Scripts/$commands_INPUT" ""
            else
                kodo_t_modular_load ".kodo/python/wpython" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Scripts/wpython" ""

                cd "$shell_DIR/.kodo" >/dev/null 2>&1 || echo ""
                
                kodo_t_modular_load ".kodo/security.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Security/security.kd" "silent" 

                kodo_t_modular_load ".kodo/compat.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Compat/compat.kd" "compat" 

                kodo_t_modular_load ".kodo/compiler.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Compiler/compiler.kd" "silent" 

                kodo_t_modular_load ".kodo/zapman.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Zapman/zapman.kd" "silent" 

                kodo_t_modular_load ".kodo/samp.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Package/samp.kd" "silent" 

                kodo_t_modular_load ".kodo/pawncc.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Package/pawncc.kd" "silent" 

                kodo_t_modular_load ".kodo/misc.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Misc/misc.kd" "silent"

                kodo_t_modular_load ".kodo/vireon.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Vireon/vireon.kd" "silent" 

                kodo_t_modular_load ".kodo/server.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Server/server.kd" "end"
            fi

            struct_kodo_t_main ""
            ;;
        "help"* | "$trigger_kd -h"* | "$trigger_kd --h"*)
            local commands_ARGS="${kd_table#"$trigger_kd -h "}"
            local commands_ARGS="${commands_ARGS#help }"
            local commands_ARGS="${commands_ARGS#"$trigger_kd --h "}"

            declare -A descriptions=(
                ["compile"]=":: Compile a project - Usage: compile | (+) [<args>] [target]"
                ["running"]=":: Running a project - Usage: running | (+) [<args>] [target]"
                ["irunn"]=":: Compile & Running a project - Usage: irunn"
                ["debug"]=":: Debug a project - Usage: debug | (+) [<args>] [target]"
                ["stop"]=":: stop all running server progress - Usage: stop"
                ["restart"]=":: Restart all Server - Usage: restart"
                ["gamemode"]=":: Download GameModes SA-MP with Selection - Usage: gamemode"
                ["pawncc"]=":: Download PawnCC SA-MP with Selection - Usage: pawncc"
                ["clear"]=":: Clear Screen Terminal - Usage: clear"
                ["checksums"]=":: Checksums of Kodo - Usage: checksums"
                ["cat"]=":: Display a files to Kodo Terminal - Usage: cat"
                ["kill"]=":: Kill a Kodo Terminal - Usage: kill"
                ["exit"]=":: Exit/End Kodo Terminal - Usage: exit | (+) [<args>] \"all\" to kill all tasks"
                ["toml"]=":: Rebuild kodo.toml - Usage: toml"
                ["directory"]=":: Display or Change Terminal Directory - Usage: directory | ls"
                ["remcac"]=":: Remove cache \".cache\" Kodo - Usage: remcac"
                ["vireon"]=":: Vireon Chat - Usage: vireon"
                ["nano"]=":: GNU/Nano Editor - Usage: nano"
                ["zapman"]=":: Kodo Mode to Zapman Mode - Usage: zapman"
                ["autoinstall"]=":: Zapman Mode | AutoInstall Package -> Usage: autoinstall"
                ["install"]=":: Zapman Mode | Install Package -> Usage: install | (+) [<args>] [url]"
                ["remove"]=":: Zapman Mode | Remove Package -> Usage: remove | (+) [<args>] [target]"
                ["sync"]=":: Sync (Upgrade) - Usage: sync | (+) [<args>] [update - only workspace]"
                ["modular"]=":: Modular Checking - Usage: modular | (+) [<args>] [target]"
                ["fetch"]=":: Fetch Kodo -> Usage: fetch"
            )
            
            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                if [[ -n "${descriptions[$commands_ARGS]}" ]]; then
                    if [[ "$commands_ARGS" == "nano" ]]; then
                        if ! command -v nano &> /dev/null; then
                            help_dialog_kd "invalid"
                        else
                            echo "${descriptions[$commands_ARGS]}"
                        fi
                    elif [[ "$commands_ARGS" == "compile" ]]; then
                        echo "${descriptions[$commands_ARGS]}"
                        echo " Example: compile bare.pwn +option_amx"
                        echo " For Option. Please See: github.com/vilksons/kodo/wiki/Compiler-Option"
                    else
                        echo "${descriptions[$commands_ARGS]}"
                    fi
                else
                    help_dialog_kd "invalid"
                fi
            else
                help_dialog_kd ""
            fi

            struct_kodo_t_main ""
            ;;
        "$trigger_kd" | "user:~$:" | "user:~$:")
            struct_kodo_t_main ""
            ;;
        "")
            struct_kodo_t_main ""
            ;;
        *)
            not_found_kd ""
            ;;
    esac
}
export mode_KODO

function not_found_kd()
{
    echo "error: $kd_table: command not found"
    if [ "$kodo_t_module_loaded" -eq 1 ]; then
        print_green "warn:" "err.. need to kill after installing \"succes\".."
        print_green " killing.."
        sleep 0.999 && SIGNAL_KILL "" && typeof ""
    else
        struct_kodo_t_main ""
    fi
}

function help_dialog_kd()
{
    local _param_=$1

    if [[ "$_param_" == "invalid" ]]; then
        echo "Invalid!.. Please Use:"
    fi

    echo "Usage: kodo <flags> | help | -h | --h | [<commands>] [<args>]"
    echo "Commands:"
    echo " | Kodo |"
    echo " compile (compile gmodes)"
    echo " running (running server)"
    echo " irunn (compile-run server)"
    echo " debug (debugging server)"
    echo " stop (stopped server)"
    echo " restart (restart server)"
    echo " gamemode (download gamemode)"
    echo " pawncc (download pawncc)"
    echo " clear (clear-screen)"
    echo " checksums (checksums of workspace)"
    echo " cat (cat file to terminal)"
    echo " kill (kill/restart terminal)"
    echo " sync (update/upgrade)"
    echo " modular (module checking)"
    echo " directory (change/display current directory)"
    echo " exit (exit from terminal)"
    echo " remcac (remove cache ~/.cache/)"
    echo " vireon (A.I Chat)"
    echo " toml (rebuild kodo.toml)"
    echo " fetch (fetch of workspace)"
    
    if command -v nano &> /dev/null; then
        echo " nano (run nano editor from terminal)"
    fi

    echo " | Zapman |"
    echo " zapman (enter Zapman)"
    echo " autoinstall (install packages from cache)"
    echo " install (install packages)"
    echo " remove (remove packages)"
    echo " exit (exit Zapman)"
}

function help_dialog_pac()
{
    echo "Usage: kodo <command> [<args>]"
    echo "Commands:"
    echo " autoinstall - Auto-Install from Zapman cache"
    echo " install     - Install/Reinstall Packages"
    echo " remove      - Remove Packages"
    echo " exit        - Exit Zapman Mode"
}

function end_kodo_t_main() {
    echo -e "$(collor_yellow "# Press any key to return.")"
    read -r -n 1 -s
    struct_kodo_t_main ""
}

: '
    @summary: Main
'
struct_kodo_t_main ""