#!/bin/bash

clear && cd "$(dirname "$(realpath "$0")")" || echo

__OS_NOTICE__=0
export __OS_NOTICE__

#  "nul"     
#  "linux"   
#  "windows" 
__OS__="nul"
export __OS__

# Server
SERVERS_NEXT=0
export SERVERS_NEXT

# Compat
__PAWNCC_NAME__="nul"
export __PAWNCC_NAME__
__SAMP_SERVER=""
export __SAMP_SERVER

# Zapman
ZAPMAN_ainstall_Encrypt=""
zapman_ainstall_SIZEOF=0
export zapman_ainstall_SIZEOF

# KCHAT
KCHAT_token_Encrypt=""
export KCHAT_token_Encrypt
DECRYPT_TOKEN=""
export DECRYPT_TOKEN

# Notice Var
console_save_messages=0
export console_save_messages
console_save_notice=0
export console_save_notice
console_module_loaded=0
export console_module_loaded

# General
shell_TITLE=""
export shell_TITLE
shell_DIR="$(dirname "$(realpath "$0")")"
export shell_DIR
shell_NAME="$(basename "$0")"
export shell_NAME

# Licenses
LICENSES="GPL v2.0 or MIT Licenses"
export LICENSES

# Compiler
__cache_save_compile=""
export __cache_save_compile

compiler_MODE="nul"
export compiler_MODE
COMPILER_PAWNCC=""
export COMPILER_PAWNCC
COMPILER_NEXT=0
export COMPILER_NEXT

commands_OPAMX=()

function collor_yellow() {
# Color Text {Yellow}
# ' echo "$(collor_yellow "label")" content '
COLOR_Y="\e[33m"
    local color="$COLOR_Y"
    local label="$1"
    echo -e "${color}${label}\e[0m"
}
export collor_yellow

function print_yellow() {
    if [ -n "$2" ]; then
        echo -e "$(collor_yellow "$1") $2"
    elif [ -z "$2" ]; then
        echo -e "$(collor_yellow "$1")"
    fi
}

function collor_green() {
# Color Text {Green}
# ' echo "$(collor_green "label")" content '
COLOR_G="\e[32m"
    local color="$COLOR_G"
    local label="$1"
    echo -e "${color}${label}\e[0m"
}
export collor_green

function print_green() {
    if [ -n "$2" ]; then
        echo -e "$(collor_green "$1") $2"
    elif [ -z "$2" ]; then
        echo -e "$(collor_green "$1")"
    fi
}

function collor_red() {
# Color Text {Red}
# ' echo "$(collor_red "label")" content '
COLOR_R="\e[91m"
    local color="$COLOR_R"
    local label="$1"
    echo -e "${color}${label}\e[0m" 
}
export collor_red

function print_red() {
    if [ -n "$2" ]; then
        echo -e "$(collor_red "$1") $2"
    elif [ -z "$2" ]; then
        echo -e "$(collor_red "$1")"
    fi
}

function collor_gray() {
# Color Text {Gray} 
# ' echo "$(collor_gray "label")" content '
COLOR_A="\e[97m"
    local color="$COLOR_A"
    local label="$1"
    echo -e "${color}${label}\e[0m"
}
export collor_gray

function print_gray() {
    if [ -n "$2" ]; then
        echo -e "$(collor_gray "$1") $2"
    elif [ -z "$2" ]; then
        echo -e "$(collor_gray "$1")"
    fi
}

function bash_title() {
    echo -ne "\033]0;$1\007"
}

function console_TITLE()
{
# Tile Functions
# ' console_TITLE "title" '
    local title=$1
    shell_TITLE="$title"
    bash_title "$shell_TITLE"
}
export console_TITLE

if [ ! -d ".cache" ]; then
    mkdir ".cache" && chmod +x ".cache"
fi

function SIGNAL_KILL()
{
    kd_table="kill"
    mode_KODO "$kd_table"
}

function ignore_this() {
    # ignore succes/error/warning to null
    "$@" > /dev/null 2>&1
}
export ignore_this

function rest_var() {
    # Reset Variables #

    : ' Checking before unset '
    [ -n "${compiler_MODE+x}" ] && unset compiler_MODE
    [ -n "${COMPILER_PAWNCC+x}" ] && unset COMPILER_PAWNCC
    [ -n "${COMPILER_NEXT+x}" ] && unset COMPILER_NEXT
    [ -n "${SERVERS_NEXT+x}" ] && unset SERVERS_NEXT

    compiler_MODE="nul"
    COMPILER_PAWNCC=""
    COMPILER_NEXT=0
    SERVERS_NEXT=0
    zapman_ainstall_SIZEOF=0
}

function @LANG_CREATE()
{
if [ ! -f "kodo.json" ]; then
    if [[ "$__SAMP_SERVER" == "samp" ]]; then
    cat > kodo.json <<EOF
{
    "amx_flags": [
        "-;+",
        "-(+",
        "-d3"
    ],
    "include_paths": "pawno/include",
    "exclude_paths": [
        "includes",
        "includes2",
        "includes3"
    ],
    "samp_log": "server_log.txt",
    "samp_config": "server.cfg",
    "samp_init": "main.pwn",
    "samp_executable": "samp03svr",
    "include_dir": "pawno/include",
    "plugins_dir": "plugins",
    "bot_token": "",
    "bot_model": "qwen-2.5-32b",
    "bot_profile": "",
    "remcache_auto": "false"
}
EOF
SIGNAL_KILL ""
    elif [[ "$__SAMP_SERVER" == "omp" ]]; then
        cat > kodo.json <<EOF
{
    "amx_flags": [
        "-;+",
        "-(+",
        "-d3"
    ],
    "include_paths": "qawno/include",
    "exclude_paths": [
        "includes",
        "includes2",
        "includes3"
    ],
    "samp_log": "log.txt",
    "samp_config": "config.json",
    "samp_init": "main.pwn",
    "samp_executable": "omp-server",
    "include_dir": "qawno/include",
    "plugins_dir": "components",
    "bot_token": "",
    "bot_model": "qwen-2.5-32b",
    "bot_profile": "",
    "remcache_auto": "false"
EOF
SIGNAL_KILL ""
    fi
else
    ignore_this @ENCRYPTION_TOKEN ""  || {
        if [ "$console_module_loaded" -eq 1 ]; then
                print_green "warn:" "err.. need to kill after installing \"succes\".."
                print_green " killing.."
                sleep 0.999
                SIGNAL_KILL ""
            fi
        }
    fi
}

function struct_console_main() {
    #
    #   @mode.Typeof
    #

    local console_missing_cmds=()
    local console_missing_save_cmds

    for console_missing_save_cmds in python3 wget curl grep awk sed tr jq aria2c openssl; do
        if ! command -v "$console_missing_save_cmds" &>/dev/null; then
            if [ "$console_missing_save_cmds" = "aria2c" ]; then
                console_missing_cmds+=("aria2")
            else
                console_missing_cmds+=("$console_missing_save_cmds")
            fi
        fi
    done

    if ((${#console_missing_cmds[@]} > 0)); then
        if [ "$console_save_notice" -ne 1 ]; then
            print_red "Can't load Workspace Module."
            print_red " Missing packages:" "${console_missing_cmds[*]}"
            printf "\e]8;;https://github.com/vilksons/kodo/wiki/Required-Packages\e\\ Please see here for more.\e]8;;\e\\"
            echo
            ignore_this sleep 1.0
            console_save_notice=1
    fi
    else
        if [ "$console_save_notice" -ne 1 ]; then
            # Recheck Sync
            if [ -f ".sync" ]; then
                : ' If there is a problem with creating the ".syncs" file, 
                    the module will be automatically reinstalled because the ".kodo" folder is deleted. '
                shred -u .sync
                if [ -d "$shell_DIR/.kodo" ]; then
                    rm -rf ".kodo"
                fi
                ignore_this sleep 0.10
            fi

            if [ ! -d ".kodo" ]; then
                mkdir ".kodo" && chmod +x ".kodo"
            fi

            function console_pack() {
                : ' Install or Load modules '
                if [ -f "$shell_DIR/$1" ] && [ "$console_module_loaded" -ne 1 ]; then
                    chmod +x "$shell_DIR/$1"
                    if [[ "$1" == ".wpython" ]]; then
                        source <(python3 .wpython 2>/dev/null) >/dev/null 2>&1 || sleep 1.0
                    else
                        source "$shell_DIR/$1" || sleep 1.0
                    fi

                    if [ "$console_module_loaded" -eq 1 ]; then
                        print_green "warn:" "err.. need to kill after installing \"succes\".."
                        print_green " killing.."
                        sleep 0.999
                        SIGNAL_KILL ""
                    fi
                else
                    console_module_loaded=1
                    
                    bash_title "Waiting resources.."

                    ignore_this mkdir -p "$shell_DIR"

                    if [ "$3" != "silent" ]; then
                        wget -q -O "$shell_DIR/$1" "$2" &>/dev/null
                    else
                        wget -q -O "$shell_DIR/$1" "$2" &>/dev/null &
                    fi

                    if [ "$3" = "end" ]; then
                        clear && cd "$(dirname "$(realpath "$0")")" || echo
                        print_yellow "install succes!"
                        console_TITLE "Kodo Mode | Usage \`kill\` to refresh"
                        typeof ""
                    fi
                fi
            }

            console_pack ".wpython" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Scripts/wpython" ""

            cd "$shell_DIR/.kodo" >/dev/null 2>&1 || echo ""
            
            console_pack ".kodo/security.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Security/security.kd" "silent" 

            console_pack ".kodo/compat.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Compat/compat.kd" "compat" 

            console_pack ".kodo/compiler.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Compiler/compiler.kd" "silent" 

            console_pack ".kodo/zapman.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Zapman/zapman.kd" "silent" 

            console_pack ".kodo/samp.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Package/samp.kd" "silent" 

            console_pack ".kodo/pawncc.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Package/pawncc.kd" "silent" 

            console_pack ".kodo/misc.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Misc/misc.kd" "silent"

            console_pack ".kodo/kchat.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/KChat/kchat.kd" "silent" 

            console_pack ".kodo/server.kd" "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Server/server.kd" "end"
            
            console_save_notice=1
        fi
    fi
    
    __cache_save_compile=".cache/compiler.log"
    export __cache_save_compile

    cd "$shell_DIR" >/dev/null 2>&1 || echo ""

    u_openmp=$(find . -maxdepth 1 -type f \( -name "omp-server" -o -name "omp-server.exe" \) | head -n 1)
    u_samp=$(find . -maxdepth 1 -type f \( -name "samp03svr" -o -name "samp-server.exe" \) | head -n 1)

    if [[ -n "$u_samp" ]] && [[ -n "$u_openmp" ]]; then
        __SAMP_SERVER="samp"
    elif [[ -n "$u_samp" ]]; then
        __SAMP_SERVER="samp"
    elif [[ -n "$u_openmp" ]]; then
        __SAMP_SERVER="omp"
    else
        __SAMP_SERVER="samp"
    fi

    ignore_this @ENCRYPTION_CREATE ""
    
    @LANG_CREATE ""
	
    rest_var ""

    typeof ""
}
export struct_console_main

function typeof() {
    if [ "$console_save_messages" -ne 1 ]; then
        console_save_messages=1
        printf "Welcome to Kodo!"
        echo
    fi
    
    if [ "$console_module_loaded" != 1 ]; then
        console_TITLE "Kodo Mode"
    fi

    HISTFILE="$HOME/.kodo.txt"
    touch "$HISTFILE"

    history -r "$HISTFILE"

    read -e -r -p "kodo:~$ " kd_table
    
    if [ -n "$kd_table" ]; then
        echo "$kd_table" >> "$HISTFILE"
    fi

    mode_KODO "$kd_table"
}
export typeof

function mode_KODO() {
    #
    #   @Send.kd-Mode
    #
    #
    
    : ' WARNING '
    #   always remember to end use 'end_console_main' or 'struct_console_main' so it doesn't crash or exit Kodo
    
    local trigger_kd="kodo"

    case "$kd_table" in
        "compile"*)
            console_TITLE "Compiler"

            local commands_ARGS="${kd_table#compile }"
            local commands_INPUT=""

            for arg in $commands_ARGS; do
                if [ -z "$commands_INPUT" ]; then
                    commands_INPUT="$arg"
                else
                    commands_OPAMX+=("$arg")
                fi
            done

            kodo_init_compilers "$commands_INPUT"

            end_console_main ""
            ;;
        "running"*)
            console_TITLE "Running"
            
            local commands_ARGS="${kd_table#running }"
            
            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                space_servers ""
            fi

            SERVERS_NEXT=1

            if [[ "$commands_INPUT" == "." ]]; then
                space_servers "" || {
                    if [ "$console_module_loaded" -eq 1 ]; then
                        print_green "warn:" "err.. need to kill after installing \"succes\".."
                        print_green " killing.."
                        sleep 0.999
                        SIGNAL_KILL ""
                    fi
                }
            else
                space_wargs_servers "$commands_INPUT" || {
                    if [ "$console_module_loaded" -eq 1 ]; then
                        print_green "warn:" "err.. need to kill after installing \"succes\".."
                        print_green " killing.."
                        sleep 0.999
                        SIGNAL_KILL ""
                    fi
                }
            fi
            end_console_main ""
            ;;
        "irunn")
            console_TITLE "Compile & Running"

            compiler_MODE="false"
            kodo_compilers "" || {
                if [ "$console_module_loaded" -eq 1 ]; then
                    print_green "warn:" "err.. need to kill after installing \"succes\".."
                    print_green " killing.."
                    sleep 0.999
                    SIGNAL_KILL ""
                fi
            }
            ;;
        "debug"*)
            console_TITLE "Debugging"

            local commands_ARGS="${kd_table#debug }"
            
            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                print_gray ":: Enter GM Name:"
                while true; do
                    read -r -p ">>> " commands_INPUT
                    [[ -n "$commands_INPUT" ]] && break
                done
            fi

            SERVERS_NEXT=2
            
            if [[ "$commands_INPUT" == "." ]]; then
                space_servers "" || {
                    if [ "$console_module_loaded" -eq 1 ]; then
                        print_green "warn:" "err.. need to kill after installing \"succes\".."
                        print_green " killing.."
                        sleep 0.999
                        SIGNAL_KILL ""
                    fi
                }
            else
                space_wargs_servers "$commands_INPUT" || {
                    if [ "$console_module_loaded" -eq 1 ]; then
                        print_green "warn:" "err.. need to kill after installing \"succes\".."
                        print_green " killing.."
                        sleep 0.999
                        SIGNAL_KILL ""
                    fi
                }
            fi
            end_console_main ""
            ;;
        "stop")
            console_TITLE "Stop"

            ignore_this pkill -9 -f "$json_EXE_SERV"

            end_console_main ""
            ;;
        "restart")
            console_TITLE "Restart"

            ignore_this pkill -9 -f "$json_EXE_SERV" && sleep 1
            space_servers ""

            end_console_main ""
            ;;
        "gamemode")
            console_TITLE "Downloads | GameMode"

            struct_choice_samp ""

            end_console_main "" || {
                if [ "$console_module_loaded" -eq 1 ]; then
                    print_green "warn:" "err.. need to kill after installing \"succes\".."
                    print_green " killing.."
                    sleep 0.999
                    SIGNAL_KILL ""
                fi
            }
            ;;
        "pawncc")
            console_TITLE "Downloads | PawnCC"

            struct_choice_pawncc ""

            end_console_main "" || {
                if [ "$console_module_loaded" -eq 1 ]; then
                    print_green "warn:" "err.. need to kill after installing \"succes\".."
                    print_green " killing.."
                    sleep 0.999
                    SIGNAL_KILL ""
                fi
            }
            ;;
        "cat"*)
            console_TITLE "Cat"

            local commands_ARGS="${kd_table#cat }"
            
            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                print_gray ":: Enter File Name:"
                while true; do
                    read -r -p ">>> " commands_INPUT
                    [[ -n "$commands_INPUT" ]] && break
                done
            fi

            cat "$commands_INPUT"
            echo
            end_console_main ""
            ;;
        "directory"*)
            console_TITLE "Directory - $shell_DIR"

            local commands_ARGS="${kd_table#directory }"
            
            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                ls -a
                end_console_main ""
            fi

            ignore_this cd "$commands_INPUT" && ls -a && shell_TITLE="directory - $shell_DIR" && bash_title "$shell_TITLE" || echo
            struct_console_main ""
            ;;
        "ls")
            ls -a
            struct_console_main ""
            ;;
        "kill")
            console_TITLE "Kill"

            console_save_notice=0
            console_save_messages=0
            
            ignore_this clear
            ignore_this sleep 0.10
            cd "$shell_DIR" || echo
            chmod +x "$shell_NAME"
            exec bash ./"$shell_NAME"
            ;;
        "sync"*)
            if [[ "$kd_table" == "sync" ]]; then
                console_TITLE "Sync"
            fi

            local commands_ARGS="${kd_table#sync }"

            local latest current
            latest=$(curl -s "https://api.github.com/repos/vilksons/kodo/commits/kodo" | grep -o '"sha": "[^"]*' | awk -F': "' '{print $2}')
            current=$(cat "$shell_DIR/.itskodo" 2>/dev/null)

            if [[ "$latest" == "$current" ]]; then
                echo "warning: $shell_NAME is up to date, Nothing to do."
                end_console_main ""
            else
                print_gray ":: New Commits Found..: Commits (SHA1): "
                echo "$latest"

                read -r -n1 -p ":: Do you want to continue Sync Kodo? [y/n] " PERMISSION_NEED_S
                echo
                [[ -z "$PERMISSION_NEED_S" ]] && PERMISSION_NEED_S="Y"

                case "$PERMISSION_NEED_S" in
                    [Yy])
                        if [[ -d "$shell_DIR/.kodo" ]]; then
                            rm -rf "$shell_DIR/.kodo"
                        fi
                        mkdir -p "$shell_DIR/.kodo"
                        chmod +x "$shell_DIR/.kodo"

                        echo "$latest" > "$shell_DIR/.itskodo"
                        
                        if  [ "$kd_table" = "sync" ]; then
                            console_TITLE "Sync | Upgrade"

                            echo "Upgrading.."
                            
                            local kodo_modular=(
                                "Security/security.kd"
                                "Compat/compat.kd"
                                "Zapman/zapman.kd"
                                "Package/samp.kd"
                                "Package/pawncc.kd"
                                "Server/server.kd"
                                "Misc/misc.kd"
                                "KChat/kchat.kd"
                                "Compiler/compiler.kd"
                            )

                            cd "$shell_DIR/.kodo" >/dev/null 2>&1 || echo ""

                            for __file__ in "${kodo_modular[@]}"; do
                                wget -q --show-progress -O "$(basename "$__file__")" \
                                    "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/$__file__" \
                                    || { touch "$shell_DIR/.sync"; }
                            done

                            cd "$shell_DIR" || echo ""
                            wget -q --show-progress -O "$shell_DIR/.wpython" \
                                "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Scripts/wpython"
                            wget -q --show-progress -O "$shell_DIR/workspace" \
                                "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Scripts/workspace"
                        elif [ "$commands_ARGS" = "update" ]; then
                            console_TITLE "Sync | Update"

                            echo "Updating.."

                            cd "$shell_DIR" || echo ""
                            wget -q --show-progress -O "workspace" \
                                "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Scripts/workspace"
                        else
                            console_TITLE "Sync | Upgrade"

                            echo "Upgrading.."
                            
                            local kodo_modular=(
                                "Security/security.kd"
                                "Compat/compat.kd"
                                "Zapman/zapman.kd"
                                "Package/samp.kd"
                                "Package/pawncc.kd"
                                "Server/server.kd"
                                "Misc/misc.kd"
                                "KChat/kchat.kd"
                                "Compiler/compiler.kd"
                            )

                            cd "$shell_DIR/.kodo" >/dev/null 2>&1 || echo ""

                            for __file__ in "${kodo_modular[@]}"; do
                                wget -q --show-progress -O "$(basename "$__file__")" \
                                    "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/$__file__" \
                                    || { touch "$shell_DIR/.sync"; }
                            done

                            cd "$shell_DIR" || echo ""
                            wget -q --show-progress -O "$shell_DIR/.wpython" \
                                "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Scripts/wpython"
                            wget -q --show-progress -O "$shell_DIR/workspace" \
                                "https://raw.githubusercontent.com/vilksons/kodo/refs/heads/kodo/Scripts/workspace"
                        fi
                        
                        chmod +x "$shell_DIR/workspace"
                        ignore_this sleep 1
                        bash "$shell_DIR/workspace"
                        ;;
                    *)
                        end_console_main ""
                        ;;
                esac
            fi
            ;;
        "lang")
            if [ -f "$shell_DIR/kodo.json" ]; then
                mv kodo.json kodo.json.old.txt
            fi

            struct_console_main ""
            ;;
        "checksums"*)
            console_TITLE "Checksums"

            local commands_ARGS="${kd_table#checksums }"

            ignore_this cd "$shell_DIR" || echo ""

            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                echo "sha1:" && sha1sum "$shell_NAME" && echo "sha256:" && sha256sum "$shell_NAME" && echo "md5:" && md5sum "$shell_NAME"
                end_console_main ""
            fi

            for algo in $commands_INPUT; do
                if [[ "$algo" == "sha1" ]]; then
                    echo "sha1:" && sha1sum "$shell_NAME"
                elif [[ "$algo" == "sha256" ]]; then
                    echo "sha256:" && sha256sum "$shell_NAME"
                elif [[ "$algo" == "md5" ]]; then
                    echo "md5:" && md5sum "$shell_NAME"
                else
                    echo "Invalid option: $algo (use sha1, sha256, md5)"
                fi
            done

            end_console_main ""
            ;;
        "exit"*)
            console_TITLE "Exit"

            local commands_ARGS="${kd_table#exit }"

            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                ignore_this sleep 0.100 &&
                bash
            fi
            bash
            ;;
        "kchat"*)
            console_TITLE "KCHAT"

            local commands_ARGS="${kd_table#kchat }"

            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                print_gray ":: Enter Question:"
                while true; do
                    read -r -p ">>> " commands_INPUT
                    [[ -n "$commands_INPUT" ]] && break
                done
            fi
            
            kodo_kchat "$commands_INPUT"
            ;;
        "nano"*)
            if ! command -v nano &> /dev/null; then
                print_red "crit:" "nano not found!, install first."
                end_console_main ""
            fi
            
            console_TITLE "GNU/Nano"
            
            local commands_ARGS="${kd_table#nano }"

            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                print_gray ":: Enter Names:"
                while true; do
                    read -r -p ">>> " commands_INPUT
                    [[ -n "$commands_INPUT" ]] && break
                done
            fi

            nano "$commands_INPUT"
            end_console_main ""
            ;;
        "remcac")
            console_TITLE "Remove Cache"

            if [ "$compiler_MODE" != "nul" ]; then
                print_red "crit:" "can't remove cache!."
                end_console_main ""
            fi

            if [ ! -f "$shell_DIR/.cache/zapman" ] && [ ! -f "$shell_DIR/.cache/compiler.log" ]; then
                echo "no cache found."
                end_console_main ""
            fi

            if [ -f "$shell_DIR/.cache/zapman" ]; then
                print_gray ":: Cache Dir: $shell_DIR/.cache/tlizapmangpac"
                read -r -p ":: Do you want to remove ALL files from $shell_DIR/.cache/zapman? [y/n] " PERMISSION_NEED_RC
                echo
                [[ -z "$PERMISSION_NEED_RC" ]] && PERMISSION_NEED_RC="Y"

                while true; do
                    case "$PERMISSION_NEED_RC" in
                        [Yy])
                            cd "$shell_DIR" || echo
                            shred -u ".cache/zapman" && print_yellow " successfully"
                            sleep 1
                            break
                            ;;
                        *)
                            echo "Operation cancelled"
                            break
                            ;;
                    esac
                done
            fi

            if [ -f "$shell_DIR/.cache/compiler.log" ]; then
                print_gray ":: Cache Dir: $shell_DIR/.cache/compiler.log"
                read -r -p ":: Do you want to remove ALL files from $shell_DIR/.cache/compiler.log? [y/n] " PERMISSION_NEED_RC
                echo
                [[ -z "$PERMISSION_NEED_RC" ]] && PERMISSION_NEED_RC="Y"

                while true; do
                    case "$PERMISSION_NEED_RC" in
                        [Yy])
                            cd "$shell_DIR" || echo
                            shred -u ".cache/compiler.log" && print_yellow " successfully"
                            sleep 1
                            end_console_main ""
                            ;;
                        *)
                            echo "Operation cancelled"
                            end_console_main ""
                            ;;
                    esac
                done
            else
                end_console_main ""
            fi
        
            ;;
        "fetch")
            fetch_now ""
            ;;
        "zapman")
            mode_KODO "" || {
                if [ "$console_module_loaded" -eq 1 ]; then
                    print_green "warn:" "err.. need to kill after installing \"succes\".."
                    print_green " killing.."
                    sleep 0.999
                    SIGNAL_KILL ""
                fi
            }
            ;;
        "clear" | "c" | "C" | "cc")
            console_save_messages=0
            clear; echo -ne "\033[3J"
            struct_console_main ""
            ;;
        "help"* | "$trigger_kd -h"* | "$trigger_kd --h"*)
            local commands_ARGS="${kd_table#"$trigger_kd -h "}"
            local commands_ARGS="${commands_ARGS#help }"
            local commands_ARGS="${commands_ARGS#"$trigger_kd --h "}"

            declare -A descriptions=(
                ["compile"]=":: Compile a project - Usage: compile | (+) [<args>] [target]"
                ["running"]=":: Running a project - Usage: running | (+) [<args>] [target]"
                ["irunn"]=":: Compile & Running a project - Usage: irunn"
                ["debug"]=":: Debug a project - Usage: debug | (+) [<args>] [target]"
                ["stop"]=":: stop all running server progress - Usage: stop"
                ["restart"]=":: Restart all Server - Usage: restart"
                ["gamemode"]=":: Download GameModes SA-MP with Selection - Usage: gamemode"
                ["pawncc"]=":: Download PawnCC SA-MP with Selection - Usage: pawncc"
                ["clear"]=":: Clear Screen Terminal - Usage: clear"
                ["checksums"]=":: Checksums of Kodo - Usage: checksums"
                ["cat"]=":: Display a files to Kodo Terminal - Usage: cat"
                ["kill"]=":: Kill a Kodo Terminal - Usage: kill"
                ["exit"]=":: Exit/End Kodo Terminal - Usage: exit | (+) [<args>] \"all\" to kill all tasks"
                ["lang"]=":: Rebuild kodo.json - Usage: lang"
                ["directory"]=":: Display or Change Terminal Directory - Usage: directory | ls"
                ["remcac"]=":: Remove cache \".cache\" Kodo - Usage: remcac"
                ["kchat"]=":: KCHAT Terminal - Usage: kchat"
                ["nano"]=":: GNU/Nano Editor - Usage: nano"
                ["zapman"]=":: Kodo Mode to Zapman Mode - Usage: zapman"
                ["sync"]=":: Sync (Upgrade) - Usage: sync | (+) [<args>] [update - only workspace]"
                ["fetch"]=":: Fetch Kodo -> Usage: fetch"
            )
            
            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$kd_table" ]]; then
                if [[ -n "${descriptions[$commands_ARGS]}" ]]; then
                    if [[ "$commands_ARGS" == "nano" ]]; then
                        if ! command -v nano &> /dev/null; then
                            help_dialog_kd "invalid"
                        else
                            echo "${descriptions[$commands_ARGS]}"
                        fi
                    elif [[ "$commands_ARGS" == "compile" ]]; then
                        echo "${descriptions[$commands_ARGS]}"
                        echo " Example: compile bare.pwn +option_amx"
                        echo " For Option. Please See: github.com/vilksons/kodo/wiki/Compiler-Option"
                    else
                        echo "${descriptions[$commands_ARGS]}"
                    fi
                else
                    help_dialog_kd "invalid"
                fi
            else
                help_dialog_kd ""
            fi

            struct_console_main ""
            ;;
        "$trigger_kd" | "user:~$:" | "user:~$:")
            struct_console_main ""
            ;;
        "")
            struct_console_main ""
            ;;
        *)
            not_found_kd ""
            ;;
    esac
}
export mode_KODO

function not_found_kd()
{
    echo "error: $kd_table: command not found"
    if [ "$console_module_loaded" -eq 1 ]; then
        print_green "warn:" "err.. need to kill after installing \"succes\".."
        print_green " killing.."
        sleep 0.999
        SIGNAL_KILL ""
    else
        struct_console_main ""
    fi
}

function help_dialog_kd()
{
    : '
        @Send.Help
    '
    local check_param=$1

    if [[ "$check_param" == "invalid" ]]; then
        echo "Invalid!.. Please Use:"
    fi

    echo "Usage: kodo <flags> | help | -h | --h | [<commands>] [<args>]"
    echo "Commands:"
    echo " compile, running, irunn (compile-run), debug (debugger)"
    echo " stop (stopped server), restart (restart server)"
    echo " gamemode, pawncc, clear (clear-screen)"
    echo " checksums, cat, zapman, kill"
    echo " sync (update/upgrade), lang, directory"

    if ! command -v nano &> /dev/null; then
        echo " exit, remcac, kchat, fetch"
    else
        echo " exit, remcac, kchat, nano, fetch"
    fi
}

function help_dialog_pac()
{
    echo "Usage: kodo <command> [<args>]"
    echo "Commands:"
    echo " autoinstall - auto Install from Zapman cache"
    echo " install     - Install/Reinstall Packages"
    echo " remove      - Remove Packages"
    echo " exit        - Exit Zapman Mode"
}

function end_console_main() {
    echo -e "$(collor_yellow "# Press any key to return.")"
    read -r -n 1 -s
    struct_console_main ""
}

: '
    @summary: Main
'
struct_console_main ""
