#!/usr/bin/env python3

import os
import hashlib
import sys
import re
import base64

def random_string(length=16):
    """Generate a random string from random bytes."""
    return base64.urlsafe_b64encode(os.urandom(length)).decode()[:length]

def wpy_sha256(input_str=None):
    """Double SHA256 hashing."""
    if input_str is None:
        input_str = random_string()  # Generate a random string if no input is provided
    
    # Convert string to bytes and hash it twice
    hash1 = hashlib.sha256(input_str.encode()).digest()
    hash2 = hashlib.sha256(hash1).hexdigest()
    
    return hash2, input_str  # Return both the hash and the original string

# Generate random words and hash them
random_word_1 = random_string(20)
RANDOM_HASH_SHA256, original_1 = wpy_sha256(random_word_1)

print(f'export RANDOM_HASH_SHA256="{RANDOM_HASH_SHA256}"')

if __name__ == '__main__':
    """ Ensure the script runs only when executed directly, not when imported """
    
    # Check if the number of command-line arguments is not equal to 2
    if len(sys.argv) != 2:
        """ Exit with no error (0) if the argument count is incorrect """
        sys.exit(0)